# permissions for end users to edit partionbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partionbinding-editor-role
rules:
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings/status
  verbs:
  - get
