# permissions for end users to view partionbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partionbinding-viewer-role
rules:
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings/status
  verbs:
  - get
