
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings/finalizers
  verbs:
  - update
- apiGroups:
  - consumer.camel.apache.org
  resources:
  - partionbindings/status
  verbs:
  - get
  - patch
  - update
